#! /bin/sh
# /home/pi/Desktop/AccessControlProject


### BEGIN INIT INFO
# Provides:		Access Control Project
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Script to start the access control program
# Description:		A script to run access control program
### END INIT INFO

case "$1" in
  start)
    echo "Starting Access Control Program"
    cd /home/pi/Desktop/AccessControlProject
    sudo python Main.py
    ;;
  stop)
   killall Main.py
   ;;
  *)
  exit 1
  ;;
esac

exit 0
